# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-19 23:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='jump_url',
            field=models.CharField(default='', max_length=100, verbose_name='\u95ea\u5c4f\u8df3\u8f6curl'),
        ),
        migrations.AddField(
            model_name='image',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0a\u4f20\u65f6\u95f4'),
        ),
    ]
