# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manage', '0002_auto_20171219_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='', max_length=50, verbose_name='\u6635\u79f0'),
        ),
    ]
