# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_manage', '0003_userprofile_nick_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '\u7528\u6237\u7ba1\u7406', 'verbose_name_plural': '\u7528\u6237\u7ba1\u7406'},
        ),
    ]
