# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manage', '0004_auto_20171220_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_desc',
            field=models.CharField(default='', max_length=5, verbose_name='\u56fe\u7247\u63cf\u8ff0'),
        ),
    ]
