# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_manage', '0002_version_add_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='version_id',
            new_name='version_code',
        ),
    ]
