# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5305\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u95ea\u5c4f\u914d\u7f6e\u7ba1\u7406',
                'verbose_name_plural': '\u95ea\u5c4f\u914d\u7f6e\u7ba1\u7406',
            },
        ),
    ]
