# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagemanage',
            options={'verbose_name': '\u5305\u7ba1\u7406', 'verbose_name_plural': '\u5305\u7ba1\u7406'},
        ),
    ]
