# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_manage', '0003_auto_20171220_1508'),
        ('image_manage', '0005_image_image_desc'),
        ('version_manage', '0002_version_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.CharField(max_length=20, verbose_name='\u53d1\u5e03\u8005')),
                ('status', models.CharField(choices=[('offline', '\u4e0b\u7ebf'), ('online', '\u4e0a\u7ebf')], default='offline', max_length=10)),
                ('pub_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('image', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='image_manage.Image', verbose_name='\u56fe\u7247')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_manage.Market', verbose_name='\u6e20\u9053')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_manage.Version', verbose_name='\u7248\u672c')),
            ],
            options={
                'verbose_name': '\u95ea\u5c4f\u914d\u7f6e\u7ba1\u7406',
                'verbose_name_plural': '\u95ea\u5c4f\u914d\u7f6e\u7ba1\u7406',
            },
        ),
    ]
