# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashconfig',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_manage.Image', verbose_name='\u56fe\u7247'),
        ),
    ]
