# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_config', '0003_flashconfig_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashconfig',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package_manage.PackageManage', verbose_name='\u5305\u540d'),
        ),
    ]
