# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-19 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6e20\u9053\u540d\u79f0')),
                ('category', models.CharField(max_length=50, verbose_name='\u7c7b\u522b')),
                ('contactor', models.CharField(default='sxf', max_length=50, verbose_name='\u8054\u7cfb\u4eba')),
            ],
            options={
                'verbose_name': '\u6e20\u9053\u7ba1\u7406',
                'verbose_name_plural': '\u6e20\u9053\u7ba1\u7406',
            },
        ),
    ]
