# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_manage', '0002_auto_20171220_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='contact',
            field=models.CharField(max_length=50, verbose_name='\u8054\u7cfb\u4eba'),
        ),
    ]
